version: "3"
services:
  app:
    container_name: app
    build: ./app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: artists_db
      MYSQL_HOSTNAME: localhost
    network_mode: host
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/